server:
  port: 7777
spring:
    application:
       name: configurator-srv
    cloud:
      config:
        server:
          git:
            uri: https://adhiveconfig@bitbucket.org/budaev123/adh.cloud.config.git
            searchPaths: '{application}/'
eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    ipAddress: ${IP_ADDRESS:127.0.0.1}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}